### ISSUE TITLE
	Actividad 7 Hilos Consola

### ISSUE THREAD

**Issue by MarcoRg06** [SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-topicos_a-4bs-idm#1]
[REPORTE DE PRACTICA EJERCICIOS DE HILOS_.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-practica-de-hilos-de-consola-topicos_a-4bs-idm/files/15095106/REPORTE.DE.PRACTICA.EJERCICIOS.DE.HILOS_.pdf)
INTEGRANTES:
Rosas García Marco Uriel 
Jiménez Sánchez Irvin
Cruz Cruz Diego

**Comment by JORGELUIS2266** [comment]
Con la rubrica el reporte cuenta con todo lo indicado fotos ,información  y una buena estructura se evalúa con un 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
